services:
  prefect-server:
    build:
      context: .
      target: development
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ./flows:/workspace/flows:cached
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_SERVER_PORT=4200
      - MLFLOW_PORT=5001
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - WORKSPACE_DIR=/workspace
      - DATA_DIR=/workspace/data
      - FLOWS_DIR=/workspace/flows
      - MLRUNS_DIR=/workspace/mlruns
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect-worker:
    build:
      context: .
      target: development
    command: prefect worker start -p default-agent-pool -t process
    depends_on:
      prefect-server:
        condition: service_healthy
    volumes:
      - ./flows:/workspace/flows:cached
      - ./data:/workspace/data:cached
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_SERVER_PORT=4200
      - MLFLOW_PORT=5001
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - WORKSPACE_DIR=/workspace
      - DATA_DIR=/workspace/data
      - FLOWS_DIR=/workspace/flows
      - MLRUNS_DIR=/workspace/mlruns

  training-worker:
    build:
      context: .
      target: development
    command: prefect agent start -q default
    depends_on:
      prefect-server:
        condition: service_healthy
    volumes:
      - .:/workspace
      - ./data:/workspace/data:cached
      - ./flows:/workspace/flows:cached
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for development
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_SERVER_PORT=4200
      - MLFLOW_PORT=5001
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - WORKSPACE_DIR=/workspace
      - DATA_DIR=/workspace/data
      - FLOWS_DIR=/workspace/flows
      - MLRUNS_DIR=/workspace/mlruns

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/workspace/mlruns:cached
    command: >
      mlflow server 
      --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_SERVER_PORT=4200
      - MLFLOW_PORT=5001
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - WORKSPACE_DIR=/workspace
      - DATA_DIR=/workspace/data
      - FLOWS_DIR=/workspace/flows
      - MLRUNS_DIR=/workspace/mlruns