services:
  prefect-server:
    extends:
      file: docker-compose.base.yml
      service: prefect-server

  training-worker:
    extends:
      file: docker-compose.base.yml
      service: training-worker
    build: 
      context: .
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api

  mlflow:
    extends:
      file: docker-compose.base.yml
      service: mlflow

networks:
  mlops-network:
    driver: bridge